import test from 'node:test';import assert from 'node:assert/strict';import {TrackingRecovery} from '../src/tracking-recovery.js';import {personCrop} from '../src/bone-comparison-data.js';import {referenceComparison} from '../src/reference-comparison-data.js';import {safeCrop,dragCrop,sourcePoint} from '../src/manual-crop.js';import {CoachVoice} from '../src/coach-voice.js';
test('first detection and short occlusion are silent, real loss needs stable recovery, repeated losses notify once',()=>{const g=new TrackingRecovery(),run=(a,b,valid)=>{let notices=0;for(let t=a;t<=b+.001;t+=.05)notices+=g.update(t,valid).resumed?1:0;return notices;};assert.equal(run(0,1,true),0);assert.equal(run(1.05,1.3,false),0);assert.equal(run(1.35,2.2,true),0);assert.equal(run(2.25,3.5,false),0);assert.equal(run(3.55,3.8,true),0);assert.equal(g.ready,false);assert.equal(run(3.85,5,true),1);assert.equal(run(5.05,6.4,false),0);assert.equal(run(6.45,8,true),1);g.reset();assert.equal(run(9,10,true),0);});
test('inference timeout acts as loss, backward clock and reset do not announce initial acquisition',()=>{const g=new TrackingRecovery();for(let t=0;t<1;t+=.05)g.update(t,true);g.update(2.5,false);assert.equal(g.update(2.6,true).resumed,false);assert.equal(g.update(2.9,true).ready,false);assert.equal(g.update(3.15,true).resumed,true);g.reset();assert.equal(g.update(5,false).resumed,false);assert.equal(g.update(0,true).resumed,false);});
test('compact legacy reference recovers frames without overwriting stored score and rejects a changed basis',()=>{const saved={version:'v1',analyzedAt:123,phases:{start:0,release:1,end:2},metrics:{x:2},frames:[{time:1}]},snapshot={version:'v1',phases:saved.phases,metrics:saved.metrics,lowQuality:true};const result=referenceComparison(snapshot,null,saved);assert.equal(result.analysis.frames,saved.frames);assert.equal(result.analysis.lowQuality,true);assert.equal(snapshot.frames,undefined);assert.equal(referenceComparison({...snapshot,metrics:{x:3}},null,saved).analysis.frames,undefined);assert.equal(referenceComparison(snapshot,{...saved,analyzedAt:100},saved).analysis.analyzedAt,100);});
test('side pose can crop without both hidden-side shoulder and hip, but actual weak Pose stays full',()=>{const f=Array.from({length:5},(_,i)=>({time:i*.1,landmarks:Array.from({length:33},(_,j)=>({x:.7+(j%3)*.015,y:.5+(j%10)*.02,visibility:[11,23].includes(j)?.1:.9}))}));assert.ok(personCrop(f).width<1);assert.equal(personCrop(f.map(f=>({...f,landmarks:f.landmarks.map(p=>({...p,visibility:.1}))}))).width,1);});
test('manual crop clamps edges, validates imported settings and maps mirrored letterboxed touch to video',()=>{const c=dragCrop({x:.98,y:.98},{x:.99,y:.99});assert.ok(safeCrop(c));assert.ok(c.x+c.width<=1);assert.equal(safeCrop({...c,width:NaN}),false);assert.equal(safeCrop({...c,width:.01}),false);assert.equal(sourcePoint(0,0,1920,1080,200,220),null);assert.deepEqual(sourcePoint(50,110,1920,1080,200,220,true),{x:.75,y:.5});});
test('recovery voice respects disabled/zero-volume and avoids cutting off active coach speech',async()=>{const spoken=[],synth={speaking:true,pending:false,speak:u=>spoken.push(u.text),cancel(){},getVoices:()=>[]},voice=new CoachVoice({synthesis:synth,Utterance:class{constructor(text){this.text=text;}}});voice.configure({enabled:false});assert.equal(voice.notify('トラッキングを再開しました'),false);voice.configure({enabled:true,volume:0});assert.equal(voice.notify('トラッキングを再開しました'),false);voice.configure({volume:1});voice.notify('トラッキングを再開しました');assert.equal(spoken.length,0);synth.speaking=false;await new Promise(r=>setTimeout(r,180));assert.deepEqual(spoken,['トラッキングを再開しました']);synth.speaking=true;voice.notify('must cancel');voice.cancel();synth.speaking=false;await new Promise(r=>setTimeout(r,180));assert.equal(spoken.length,1);});

test('reacquisition waiting is not added to a sub-second loss duration',()=>{const g=new TrackingRecovery();for(let t=0;t<1;t+=.05)g.update(t,true);for(let t=1;t<1.8;t+=.05)g.update(t,false);assert.equal(g.update(1.85,true,false).resumed,false);assert.equal(g.update(2.1,true,true).resumed,false);assert.equal(g.update(2.4,true,true).resumed,false);assert.equal(g.update(2.65,true,true).resumed,false);});
