import test from 'node:test';
import assert from 'node:assert/strict';
import {frames} from '../test-support/shot-frames.js';
import {calculateMetrics} from '../src/metrics.js';
import {reviewShot} from '../src/shot-engine.js';
import {emptyReviewData,collectCases,referenceCatalog,exportReviewData,validateReviewImport,mergeReviewImport,evaluationReport} from '../src/review-data.js';
const metadata={shotType:'jump',cameraAngle:'side',hand:'right'};
function fixture(){const analysis=calculateMetrics(frames(),{start:0,release:1,end:2},'right',1,false),review=reviewShot(analysis,analysis,metadata,metadata),video={id:'good',title:'Good',...metadata,analysis,createdAt:100};
 const single={id:'one',referenceVideoId:'good',newVideoId:'new',referenceTitle:'Good',referenceMeta:metadata,newMeta:metadata,referenceAnalysis:analysis,newAnalysis:analysis,...review,createdAt:200};
 const session={id:'practice',title:'Practice',videoId:'practice-video',referenceVideoId:'good',referenceTitle:'Good',referenceMeta:metadata,referenceAnalysis:analysis,metadata,shots:[{number:1,newAnalysis:analysis,...review}],createdAt:300};
 const live={id:'camera',goodFormReference:video,metadata,shots:[{number:1,analysis,...review,coachFeedback:{code:'perfect',text:{ja:'パーフェクト',en:'Perfect'},reason:'Score ≥95',speak:true}}],createdAt:400};return {video,single,session,live};}
test('three analysis modes become linked reusable cases without changing existing results',()=>{const f=fixture(),before=structuredClone(f);const cases=collectCases([f.single],[f.session],[f.live]);assert.equal(cases.length,3);assert.deepEqual(f,before);for(const c of cases){assert.equal(c.goodFormReference.id,'good');assert.equal(c.scoreVersion,f.single.comparison.version);assert.equal(c.analysis.frames,undefined);assert.equal(c.comparison.overall,100);assert.equal(c.aiInterpretation,null);}assert.deepEqual(new Set(cases.map(c=>c.id)),new Set(['single:one','session:practice:1','live:camera:1']));});
test('manual labels remain distinct from scores, automated outcomes and excluded Session rows',()=>{const f=fixture(),cases=collectCases([f.single],[],[]),c=cases[0];c.labels={detection:'false-positive',evaluation:'disagree',outcome:'missed',notes:'Review'};const collected=collectCases([f.single],[],[],{[c.id]:c});assert.equal(collected[0].comparison.overall,100);assert.equal(collected[0].labels.outcome,'missed');assert.equal(f.single.comparison.overall,100);assert.equal(f.single.newAnalysis.outcome,undefined);});
test('multiple references preserve category metadata and immutable historic reference snapshots',()=>{const f=fixture(),other={...f.video,id:'other',cameraAngle:'front'};const catalog=referenceCatalog([f.video,other],[f.single],[],[],'other');assert.deepEqual(Object.keys(catalog).sort(),['good','other']);f.video.analysis.metrics.wristHeight=-4;assert.notEqual(catalog.good.analysis.metrics.wristHeight,-4);const cases=collectCases([f.single],[],[]);const data=emptyReviewData();data.cases[cases[0].id]=cases[0];const old=data.cases[cases[0].id].comparison.overall;catalog.good.analysis.version='future';assert.equal(data.cases[cases[0].id].comparison.overall,old);});
test('portable JSON round trip retains measurements, original coach text, labels, version and references',()=>{const f=fixture(),data=emptyReviewData();data.references.good=f.video;const cases=collectCases([f.single],[f.session],[f.live]);cases[0].humanFeedback=[{id:'human',coachName:'Coach',originalComment:'Do not paraphrase <original>',observedIssue:'release',priorityCorrection:'release height',practiceCue:'raise',agreement:'disagree',improvementNotes:'later',appFeedbackSnapshot:{text:'Original app text'},aiInterpretation:null}];const exported=JSON.parse(JSON.stringify(exportReviewData(data,cases)));const imported=validateReviewImport(exported);assert.equal(Object.keys(imported.cases).length,3);assert.equal(imported.cases[cases[0].id].humanFeedback[0].originalComment,'Do not paraphrase <original>');assert.deepEqual(imported.references.good.analysis.metrics,f.video.analysis.metrics);assert.equal(imported.cases[cases[0].id].analysis.frames,undefined);});
test('import adds new IDs without overwriting conflicting local annotations or scores',()=>{const f=fixture(),cases=collectCases([f.single],[],[]),a=emptyReviewData();a.cases[cases[0].id]=cases[0];const b=structuredClone(a);b.cases[cases[0].id].labels.notes='foreign';b.references.good=f.video;const result=mergeReviewImport(a,b);assert.equal(result.added,1);assert.equal(result.skipped,1);assert.equal(result.data.cases[cases[0].id].labels.notes,'');assert.equal(Object.keys(a.references).length,0);});
test('import rejects unsafe keys, invalid labels, scores and incompatible schema before storage',()=>{const f=fixture(),base=exportReviewData(emptyReviewData(),collectCases([f.single],[],[]));for(const mutate of [b=>b.version=2,b=>b.data.cases['single:one'].labels.detection='true',b=>b.data.cases['single:one'].comparison.overall=999,b=>b.data.references.bad={id:'bad'},b=>b.data.cases['single:one'].appFeedback.original.focus='text']){const b=structuredClone(base);mutate(b);assert.throws(()=>validateReviewImport(b));}const unsafe=JSON.parse(JSON.stringify(base).replace('"version":1','"__proto__":{"polluted":true},"version":1'));assert.throws(()=>validateReviewImport(unsafe));assert.equal({}.polluted,undefined);});
test('precision uses reviewed predictions only; recall requires independent count and complete labels',()=>{const f=fixture(),base=collectCases([],[f.session],[])[0],cases=[1,2,3,4].map(n=>({...structuredClone(base),id:`session:practice:${n}`})),data=emptyReviewData();cases[0].labels.detection='correct';cases[1].labels.detection='correct';cases[2].labels.detection='false-positive';assert.equal(evaluationReport(cases,data).detection.precision,2/3);assert.equal(evaluationReport(cases,data).detection.recall,null);data.verification['session:practice']={actualShots:4,complete:true};assert.equal(evaluationReport(cases,data).detection.recall,null);cases[3].labels.detection='false-positive';const r=evaluationReport(cases,data);assert.equal(r.detection.recall,.5);assert.equal(r.detection.byMode.session.precision,.5);assert.equal(r.detection.byMode.single.precision,null);assert.equal(r.detection.falseNegatives,2);data.verification['session:practice'].actualShots=1;assert.equal(evaluationReport(cases,data).detection.recall,null);});
test('human agreement excludes unsure; zero data remains N/A, confidence/score distributions retain sample counts',()=>{const f=fixture(),c=collectCases([f.single],[],[])[0],data=emptyReviewData();c.humanFeedback=[{agreement:'agree'},{agreement:'disagree'},{agreement:'unsure'}];data.sessionFeedback.scope={comments:[{agreement:'agree'}]};const r=evaluationReport([c],data);assert.equal(r.human.agreement,2/3);assert.equal(r.human.unsure,1);assert.deepEqual(r.distribution,[0,0,0,0,1]);assert.equal(r.confidence.High,1);assert.equal(evaluationReport([],emptyReviewData()).human.agreement,null);});
test('weak session rating export/import preserves separate shot labels and rejects mismatched targets',async()=>{
 const {ratingEntry}=await import('../src/session-feedback.js'),f=fixture(),data=emptyReviewData(),cases=collectCases([],[],[f.live]);data.sessionFeedback['live:camera']=ratingEntry(f.live,null,{dip:'inaccurate',release:'unknown',trunk:'accurate'},'session note','condition',null,1);const exported=exportReviewData(data,cases),loaded=validateReviewImport(JSON.parse(JSON.stringify(exported)));assert.equal(loaded.sessionFeedback['live:camera'].batchRating.ratings.dip,'inaccurate');assert.equal(loaded.cases['live:camera:1'].labels.detection,'unreviewed');
 const bad=structuredClone(exported);bad.data.sessionFeedback['live:camera'].batchRating.sessionId='other';assert.throws(()=>validateReviewImport(bad));
});
test('optional points metadata round trips without changing legacy cases, and invalid point labels are rejected',()=>{
 const f=fixture();for(const points of [undefined,'unspecified','2pt','3pt']){const live={...f.live,metadata:{...f.live.metadata,...(points===undefined?{}:{points})}},cases=collectCases([],[],[live]),json=exportReviewData(emptyReviewData(),cases),read=validateReviewImport(JSON.parse(JSON.stringify(json)));assert.equal(read.cases['live:camera:1'].metadata.points,points);}
 const json=exportReviewData(emptyReviewData(),collectCases([],[],[f.live]));json.data.cases['live:camera:1'].metadata.points='guessed';assert.throws(()=>validateReviewImport(json));
});
