// Browser checks with generated video/camera frames. No physical iPhone validation.
import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('playwright'),version=require('../package.json').version;
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
try{
 const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{
  window.__requests=[];window.__readTimes=[];window.__ring=true;const read=CanvasRenderingContext2D.prototype.getImageData;CanvasRenderingContext2D.prototype.getImageData=function(...args){window.__readTimes.push(performance.now());return read.apply(this,args);};
  navigator.mediaDevices.getUserMedia=async c=>{window.__requests.push(c);if(window.__fallback&&c.video!==true)throw new DOMException('no front','OverconstrainedError');const canvas=document.createElement('canvas');canvas.width=320;canvas.height=480;const ctx=canvas.getContext('2d');const paint=()=>{ctx.fillStyle='#207744';ctx.fillRect(0,0,320,480);if(window.__ring){ctx.strokeStyle='#dc5514';ctx.lineWidth=5;ctx.strokeRect(90,80,80,20);}};paint();const timer=setInterval(paint,40),s=canvas.captureStream(25),t=s.getVideoTracks()[0],stop=t.stop.bind(t);t.stop=()=>{clearInterval(timer);stop();};t.getSettings=()=>({facingMode:c.video===true?'environment':c.video.facingMode.ideal});return s;};
  window.Pose=class{setOptions(){}async initialize(){}onResults(cb){this.cb=cb;}async close(){}async send(){this.cb({poseLandmarks:null});}};
 });
 const base=process.env.LIVE_TEST_URL||'http://127.0.0.1:5173';await page.goto(base);
 await page.evaluate(async()=>{
  const c=document.createElement('canvas');c.width=160;c.height=240;const ctx=c.getContext('2d'),stream=c.captureStream(20),chunks=[];const rec=new MediaRecorder(stream);rec.ondataavailable=e=>chunks.push(e.data);const done=new Promise(r=>rec.onstop=r);ctx.fillStyle='#22cc44';ctx.fillRect(0,0,160,240);rec.start();const timer=setInterval(()=>{ctx.fillStyle='#22cc44';ctx.fillRect(0,0,160,240);},50);await new Promise(r=>setTimeout(r,700));rec.stop();await done;clearInterval(timer);stream.getTracks().forEach(t=>t.stop());
  const {saveVideo,setSetting}=await import('/src/storage.js');await saveVideo({id:'thumb7',title:'旧Good Form',createdAt:1,shotType:'jump',cameraAngle:'side',hand:'right',analysis:{phases:{release:.3}},blob:new Blob(chunks,{type:rec.mimeType})});await setSetting('referenceId','thumb7');await setSetting('issue7-preserve',{labels:['correct'],settings:'keep'});
 });await page.reload();await page.waitForSelector('#good-thumbnail canvas');
 assert.equal(await page.locator('#good-thumbnail canvas').evaluate(c=>{const p=c.getContext('2d').getImageData(40,48,1,1).data;return p[1]>150&&p[0]<80;}),true);
 await page.locator('#manage-good').click();await page.waitForSelector('[data-good-thumbnail] canvas');assert.equal(await page.locator('[data-good-thumbnail] canvas').evaluate(c=>{const p=c.getContext('2d').getImageData(32,40,1,1).data;return p[1]>150;}),true);
 for(const tab of ['good','review','calibration','coach']){await page.locator(`[data-page="${tab}"]`).click();assert.equal(await page.locator('.app-version').textContent(),`v${version}`);assert.equal(await page.locator('.app-version').isVisible(),true);}
 await page.locator('#live-start').click();await page.waitForFunction(()=>document.querySelector('#live-hoop-status').textContent.includes('自動候補'));
 assert.equal(await page.evaluate(()=>window.__requests[0].video.facingMode.ideal),'user');assert.match(await page.locator('#live-video').getAttribute('style'),/scaleX\(-1\)/);
 await page.locator('.camera-settings').evaluate(e=>e.open=true);await page.locator('#live-object-tools').evaluate(e=>e.open=true);await page.locator('#live-video').scrollIntoViewIfNeeded();const marker=await page.evaluate(async()=>{const v=document.querySelector('#live-video'),r=v.getBoundingClientRect(),{videoTransform}=await import('/src/pose-coordinates.js'),t=videoTransform(v.videoWidth,v.videoHeight,r.width,r.height,true);return {x:r.left+t.x({x:130/320}),y:r.top+t.y({y:90/480})};});const touch=await page.context().newCDPSession(page);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:marker.x,y:marker.y}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:marker.x+15,y:marker.y+8}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touch.detach();assert.match(await page.locator('#live-hoop-status').textContent(),/位置を補正・未確定/);await page.locator('#live-hoop-confirm').click();assert.match(await page.locator('#live-hoop-status').textContent(),/確定済み/);
 const count=await page.evaluate(()=>window.__readTimes.length);await page.waitForTimeout(1500);assert.equal(await page.evaluate(()=>window.__readTimes.length),count);
 await page.locator('#live-switch').click();await page.waitForFunction(()=>document.querySelector('#live-camera-name').textContent.includes('背面'));assert.equal(await page.locator('#live-video').evaluate(v=>v.style.transform),'none');
 await page.evaluate(()=>{window.__ring=false;window.dispatchEvent(new Event('orientationchange'));});await page.waitForFunction(()=>document.querySelector('#live-hoop-status').textContent.includes('候補なし'),null,{timeout:7000});assert.equal(await page.locator('#live-hoop-confirm').isDisabled(),true);
 await page.locator('#live-hoop-set').click();await page.locator('#live-video').scrollIntoViewIfNeeded();let rect=await page.locator('#live-video').boundingBox();await page.mouse.move(rect.x+rect.width*.3,rect.y+rect.height*.3);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.6,rect.y+rect.height*.35);await page.mouse.up();assert.match(await page.locator('#live-hoop-status').textContent(),/手動候補・未確定/);await page.locator('#live-hoop-confirm').click();assert.match(await page.locator('#live-hoop-status').textContent(),/確定済み/);
 await page.locator('#live-stop').click();await page.evaluate(()=>window.__fallback=true);await page.locator('#live-start').click();await page.waitForFunction(()=>document.querySelector('#live-camera-name').textContent.includes('背面'));assert.equal(await page.evaluate(()=>window.__requests.at(-1).video),true);await page.locator('#live-stop').click();
 await page.locator('[data-page="calibration"]').click();await page.waitForSelector('#ai-evidence');assert.equal(await page.locator('#ai-evidence').evaluate(e=>e.open),false);await page.locator('#ai-generate').click();await page.waitForFunction(()=>document.querySelector('#ai-message').textContent.includes('まだ検証に必要'));assert.equal(await page.locator('#ai-evidence').evaluate(e=>e.open),true);assert.match(await page.locator('.ai-preparation').textContent(),/2回以上の練習/);assert.match(await page.locator('#ai-evidence').textContent(),/確認済みのシュート本数/);assert.equal(await page.locator('[data-approve]').count(),0);
 for(const size of [{width:320,height:740},{width:390,height:844},{width:430,height:932},{width:844,height:390}]){await page.setViewportSize(size);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('.app-version').isVisible(),true);assert.ok((await page.locator('#ai-review').boundingBox()).height>=44);}
 assert.deepEqual(await page.evaluate(async()=>(await (await import('/src/storage.js')).getSetting('issue7-preserve')).value),{labels:['correct'],settings:'keep'});
 await page.evaluate(async()=>{const {listVideos,saveVideo}=await import('/src/storage.js');const v=(await listVideos()).find(v=>v.id==='thumb7');await saveVideo({...v,blob:new Blob(['bad'],{type:'video/mp4'})});});await page.reload();await page.waitForFunction(()=>document.querySelector('#good-thumbnail')?.textContent.includes('読み込めません'));assert.equal(await page.locator('.good-thumbnail').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS Issue #7: version/all tabs, decoded and invalid old Good Form thumbnails, front/mirror/rear/fallback, automatic Hoop candidate/confirm/no candidate/manual correction/rotation/bounded scans, compact AI insufficient-data units, preserved settings, 320–430px/landscape. Physical iPhone Safari untested.');
}finally{await browser.close();}
