import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright');
const base=process.env.APP_URL??'http://127.0.0.1:5173';
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:390,height:844},timezoneId:'Asia/Tokyo'}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(base+'/');
const before=await page.evaluate(async()=>{
 const st=await import('/src/storage.js'),{frames}=await import('/test-support/shot-frames.js'),{calculateMetrics}=await import('/src/metrics.js'),{reviewShot}=await import('/src/shot-engine.js'),{collectCases,emptyReviewData}=await import('/src/review-data.js'),{defaultParameters,scopeKey,CALIBRATION_ENGINE}=await import('/src/personal-calibration.js');
 const metadata={shotType:'jump',cameraAngle:'side',hand:'right'},analysis=calculateMetrics(frames(),{start:0,release:1,end:2},'right',1,false),reference={id:'good',title:'Synthetic Good Form',...metadata,analysis,isGoodForm:true},review=reviewShot(analysis,analysis,metadata,metadata),now=Date.now();
 const make=(id,time,score,count=30)=>({id,kind:'live-coach',version:'live-coach-0.6',createdAt:time,endedAt:time+1,metadata,goodFormReference:reference,calibrationVersionId:'old-approved',shots:Array.from({length:count},(_,i)=>({number:i+1,timestamp:time+i,analysis,scoreVersion:review.comparison.version,comparison:{...review.comparison,overall:score,confidence:i===29?'Low':'High',metrics:review.comparison.metrics.map(m=>({...m,score:score}))},trunkEstimate:{version:'trunk-proxy-1',status:'estimated',confidence:'Medium',lean:15,extension:170,excess:8,changeExcess:8,alert:true,audioEligible:true,persistentSeconds:.2,reason:'Fixture'},coachFeedback:{version:'live-coach-0.6',speak:true,text:{ja:'グッド！',en:'Good'},reason:'Fixture'}}))});
 const sessions=[make('previous',now-2*86400000,70),make('current',now-1000,80),make('empty',now-4*86400000,80,0)];
 await st.saveVideo(reference);await st.setSetting('referenceId','good');for(const s of sessions)await st.saveCoachSession(s);
 const data=emptyReviewData();data.cases=Object.fromEntries(collectCases([],[],sessions).map(c=>[c.id,c]));data.sessionFeedback['live:current']={mode:'live',recordId:'current',title:'Synthetic Good Form',appFeedback:{text:'Original comment context'},comments:[{id:'comment',createdAt:1,coachName:'Fixture',originalComment:'Original note',agreement:'unsure',observedIssue:'',priorityCorrection:'',practiceCue:'',improvementNotes:''}]};await st.setSetting('review-v04',data);
 await st.savePoseSession({id:'pose-old',count:1,bytes:180,chunks:1});await st.saveTemporaryVideo({id:'retained-video',sessionId:'unused',bytes:3,blob:new Blob(['old']),keep:true});
 await st.commitCalibration({id:'old-approved',scope:scopeKey(metadata,'good'),engine:CALIBRATION_ENGINE,kind:'feedback',createdAt:1,parameters:defaultParameters(),trainingIds:['train'],validationIds:['validation']});
 return {results:JSON.stringify(await st.listResults()),cases:JSON.stringify(data.cases),versions:JSON.stringify(await st.listCalibrations()),pose:JSON.stringify(await st.listPoseSessions()),videos:(await st.listVideos()).length};
});
async function openReport(id='current'){await page.locator('.other-menu').evaluate(e=>e.open=true);await page.locator('[data-page=history]').click();await page.locator(`[data-coach="${id}"]`).click();await page.waitForSelector('#batch-save');}
await page.reload();await openReport();assert.match(await page.locator('.report-overview').innerText(),/80\.0%/);assert.match(await page.locator('.report-overview').innerText(),/30本/);assert.match(await page.locator('.report-overview').innerText(),/29 \/ 1本/);assert.match(await page.locator('.report-overview').innerText(),/\+10\.0pt/);
await page.locator('input[name=batch-dip][value=inaccurate]').check();await page.locator('input[name=batch-release][value=accurate]').check();await page.locator('#batch-note').fill('全体評価のみ <script>fixture</script>');await page.locator('#batch-save').click();await page.waitForFunction(()=>document.querySelector('#batch-status').textContent.includes('保存しました'));
await page.reload();await openReport();assert.equal(await page.locator('input[name=batch-dip][value=inaccurate]').isChecked(),true);assert.match(await page.locator('#batch-note').inputValue(),/全体評価のみ/);
await page.locator('input[name=batch-dip][value=accurate]').check();await page.locator('#batch-save').click();await page.waitForFunction(()=>document.querySelector('#batch-status').textContent.includes('保存しました'));
const after=await page.evaluate(async()=>{const st=await import('/src/storage.js'),data=(await st.getSetting('review-v04')).value;return {results:JSON.stringify(await st.listResults()),cases:JSON.stringify(data.cases),versions:JSON.stringify(await st.listCalibrations()),pose:JSON.stringify(await st.listPoseSessions()),videos:(await st.listVideos()).length,temp:(await st.listTemporaryVideos()).length,data};});
for(const k of ['results','cases','versions','pose','videos'])assert.equal(after[k],before[k]);assert.equal(after.temp,1);assert.equal(Object.keys(after.data.sessionFeedback).length,1);assert.equal(after.data.sessionFeedback['live:current'].comments[0].originalComment,'Original note');assert.equal(after.data.sessionFeedback['live:current'].batchRating.ratings.dip,'accurate');
// Export/import validation retains new batch fields and old labels/comments.
assert.equal(await page.evaluate(async()=>{const {exportReviewData,validateReviewImport}=await import('/src/review-data.js'),st=await import('/src/storage.js'),data=(await st.getSetting('review-v04')).value;return validateReviewImport(JSON.parse(JSON.stringify(exportReviewData(data,Object.values(data.cases))))).sessionFeedback['live:current'].batchRating.ratings.dip;}),'accurate');
await page.locator('[data-my-progress=current]').click();await page.waitForSelector('#progress-chart svg');assert.match(await page.locator('#progress-chart').innerText(),/75\.0%/);assert.match(await page.locator('#progress-chart').innerText(),/58本/);await page.locator('#progress-unit').selectOption('month');await page.locator('#progress-days').selectOption('7');await page.locator('#progress-item').selectOption('trunk');assert.match(await page.locator('#progress-chart').innerText(),/15\.0°/);assert.doesNotMatch(await page.locator('#progress-chart').innerText(),/15\.0%/);
await page.locator('details:has(#progress-weak)').evaluate(e=>e.open=true);await page.waitForFunction(()=>document.querySelector('#progress-weak').textContent.includes('1回のセッション'));assert.match(await page.locator('#progress-weak').innerText(),/正確 1回/);
for(const width of [320,390,430]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await openReport();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('details:has(.report-items)').evaluate(e=>e.open=true);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('[data-my-progress=current]').click();await page.waitForSelector('#progress-chart');}
await openReport('empty');assert.match(await page.locator('.report-overview').innerText(),/—/);assert.doesNotMatch(await page.locator('.report-overview').innerText(),/0\.0%/);assert.equal(await page.locator('.tabs>button').count(),4);
// Existing session-comment editing preserves batch feedback.
await page.locator('[data-page=review]').click();await page.locator('.review-tools').evaluate(e=>e.open=true);await page.locator('#review-library').click();await page.locator('#library-target').selectOption('scope:live:current');await page.locator('[name=coachName]').fill('Second coach');await page.locator('[name=originalComment]').fill('Additional comment');await page.locator('#library-coach-form button').click();await page.waitForFunction(()=>document.querySelector('#review-status').textContent.includes('保存しました'));
assert.equal(await page.evaluate(async()=>{const st=await import('/src/storage.js');return (await st.getSetting('review-v04')).value.sessionFeedback['live:current'].batchRating.ratings.dip;}),'accurate');
assert.deepEqual(errors,[]);console.log(JSON.stringify({thirtyShotReport:true,previousDelta:true,batchSaveEditReload:true,weakDoesNotChangeShotsOrCalibration:true,oldDataAndCommentsKept:true,exportImport:true,weightedProgress:true,weekMonthAndTrunkUnits:true,portraitWidths:[320,390,430],pageErrors:errors,physicalSafari:'not verified'}));await browser.close();
