// Optional Chromium check; no physical camera, real canvas stream / MediaRecorder.
import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
try{
 const page=await browser.newPage({viewport:{width:390,height:844},timezoneId:'Asia/Tokyo'}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.addInitScript(()=>{
  window.__mode='none';window.__tracks=[];window.__spoken=[];window.__ball=true;window.__objectReads=[];const read=CanvasRenderingContext2D.prototype.getImageData;CanvasRenderingContext2D.prototype.getImageData=function(...args){window.__objectReads.push(performance.now());return read.apply(this,args);};window.__poseSends=0;window.__maxSends=0;window.__sends=0;
  Object.defineProperty(window,'speechSynthesis',{value:{cancel(){},getVoices(){return []},speak(u){window.__spoken.push(u.text);}}});
  navigator.mediaDevices.getUserMedia=async constraints=>{if(window.__deny)throw new DOMException('denied','NotAllowedError');const c=document.createElement('canvas');c.width=320;c.height=480;const ctx=c.getContext('2d');let n=0;const draw=()=>{ctx.fillStyle=n++%2?'#254638':'#294b3d';ctx.fillRect(0,0,320,480);if(window.__ball){ctx.fillStyle='#d47a28';ctx.beginPath();ctx.arc(.59*320,.06*480,12,0,Math.PI*2);ctx.fill();}};draw();const timer=setInterval(draw,33),s=c.captureStream(30),t=s.getVideoTracks()[0],stop=t.stop.bind(t);t.stop=()=>{clearInterval(timer);stop();};t.getSettings=()=>({facingMode:constraints.video.facingMode.ideal});window.__tracks.push(t);return s;};
  window.Pose=class{setOptions(){}async initialize(){this.start=performance.now();}onResults(f){this.cb=f;}async close(){}async send(){window.__sends++;window.__maxSends=Math.max(window.__maxSends,window.__sends);window.__poseSends++;await new Promise(r=>setTimeout(r,10));const time=(performance.now()-this.start)/1000,v=window.__mode==='static'?1:Math.min(1,time%4);const p=Array.from({length:33},()=>({x:.5,y:.5,visibility:.99}));for(const [s,e,w,h,k,a]of[[11,13,15,23,25,27],[12,14,16,24,26,28]]){p[s]={x:.5,y:.35,visibility:.99};p[e]={x:.58,y:.35-.12*v,visibility:.99};p[w]={x:.62-.03*v,y:.44-.38*v,visibility:.99};p[h]={x:.5,y:.6-.04*v,visibility:.99};p[k]={x:.63-.12*v,y:.75,visibility:.99};p[a]={x:.5,y:.95,visibility:.99};}if(window.__mode==='partial')p[16].visibility=.1;this.cb({poseLandmarks:window.__mode==='none'?null:p});window.__sends--;}};
 });
 await page.goto(process.env.LIVE_TEST_URL||'http://127.0.0.1:5173/');
 await page.evaluate(async()=>{const {calculateMetrics}=await import('/src/metrics.js'),{frames}=await import('/test-support/shot-frames.js'),{saveVideo,setSetting}=await import('/src/storage.js');await saveVideo({id:'g5',title:'基準5',createdAt:1,shotType:'jump',cameraAngle:'side',hand:'right',analysis:calculateMetrics(frames(),{start:0,release:1,end:2},'right',2/3),blob:new Blob()});await setSetting('referenceId','g5');await setSetting('issue5-preserve',{comments:'旧記録',calibration:'保持'});});await page.reload();
 await page.getByRole('button',{name:'Live Coach',exact:true}).click();assert.equal(await page.locator('#coach-record').isChecked(),true);await page.locator('#coach-points').selectOption('3pt');await page.locator('#live-start').click();await page.waitForFunction(()=>!document.querySelector('#coach-start').disabled);await page.locator('#coach-start').click();
 await page.waitForTimeout(1600);assert.equal(await page.locator('#coach-count').textContent(),'0');assert.match(await page.locator('#coach-presence').textContent(),/人物を検出していません/);assert.equal(await page.locator('.coach-setup').evaluate(e=>e.open),false);
 for(const size of [{width:320,height:740},{width:390,height:844},{width:430,height:932},{width:844,height:390}]){await page.setViewportSize(size);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('#coach-stop').isVisible(),true);await page.locator('.coach-workspace').scrollIntoViewIfNeeded();const positions=await page.evaluate(()=>{const a=document.querySelector('#live-video').getBoundingClientRect(),b=document.querySelector('.coach-hud').getBoundingClientRect(),f=document.querySelector('#coach-feedback').getBoundingClientRect(),stop=document.querySelector('#coach-stop').getBoundingClientRect();return {a:a.x,b:b.x,bottom:b.bottom,feedbackBottom:f.bottom,stopTop:stop.top};});if(size.width>size.height)assert.ok(positions.a<positions.b);else {assert.ok(positions.feedbackBottom<=size.height,JSON.stringify({size,positions}));assert.ok(positions.stopTop>=0);}if(size.width===390)await page.screenshot({path:'/workspace/work/issue5-portrait.png'});}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.__mode='static');await page.locator('.camera-settings').evaluate(e=>e.open=true);await page.locator('#live-object-tools').evaluate(e=>e.open=true);await page.locator('#live-ball-enable').check();await page.waitForFunction(()=>document.querySelector('#live-ball-status').textContent.includes('候補'));assert.equal(await page.evaluate(()=>window.__maxSends),1);const reads=await page.evaluate(()=>window.__objectReads);assert.ok(reads.length>0);assert.ok(reads.filter((t,i)=>i&&t-reads[i-1]<190).length<=3);
 await page.evaluate(()=>window.__ball=false);await page.waitForFunction(()=>document.querySelector('#live-ball-status').textContent==='ボール未検出');await page.locator('#live-hoop-set').click();const rect=await page.locator('#live-video').boundingBox();const x=rect.x+rect.width/2,y=rect.y+rect.height/2;await page.mouse.click(x-15,y-8);await page.mouse.click(x+15,y+8);assert.match(await page.locator('#live-hoop-status').textContent(),/手動候補・未確定/);await page.locator('#live-hoop-set').click();await page.mouse.move(x-20,y-10);await page.mouse.down();await page.mouse.move(x+20,y+10);await page.mouse.up();assert.match(await page.locator('#live-hoop-status').textContent(),/手動候補・未確定/);await page.locator('#live-hoop-confirm').click();assert.match(await page.locator('#live-hoop-status').textContent(),/確定済み/);await page.evaluate(()=>window.dispatchEvent(new Event('orientationchange')));assert.match(await page.locator('#live-hoop-status').textContent(),/未指定/);
 await page.evaluate(()=>window.__mode='partial');await page.waitForTimeout(1200);assert.equal(await page.locator('#coach-count').textContent(),'0');await page.evaluate(()=>window.__mode='none');await page.waitForTimeout(500);await page.evaluate(()=>window.__mode='auto');await page.locator('.camera-settings').evaluate(e=>e.open=false);await page.waitForFunction(()=>Number(document.querySelector('#coach-count').textContent)>=2,null,{timeout:16000});await page.locator('#coach-stop').click();await page.waitForSelector('.session-report');assert.match(await page.locator('.session-report').textContent(),/3ポイント/);
 const saved=await page.evaluate(async()=>{const {listResults,listTemporaryVideos,getSetting}=await import('/src/storage.js');return {s:(await listResults()).find(s=>s.kind==='live-coach'),videos:(await listTemporaryVideos()).map(r=>({start:r.start,end:r.end,bytes:r.bytes})),old:(await getSetting('issue5-preserve')).value};});assert.equal(saved.s.metadata.points,'3pt');assert.ok(saved.videos.length);assert.equal(saved.s.recordingStatus,'stopped');assert.equal(saved.old.comments,'旧記録');for(let i=1;i<saved.s.shots.length;i++)assert.ok(saved.s.shots[i-1].videoRange.end<=saved.s.shots[i].videoRange.start);
 await page.locator('.coach-setup').evaluate(e=>e.open=true);await page.locator('#coach-record').uncheck();await page.waitForFunction(()=>document.querySelector('#record-status').textContent.includes('次回もOFF'));await page.reload();await page.getByRole('button',{name:'Live Coach',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#coach-record').checked);assert.equal(await page.locator('#coach-record').isChecked(),false);
 await page.getByRole('button',{name:'Shot Review',exact:true}).click();await page.locator('[data-review-case]').first().click();await page.waitForSelector('#clip-player:not([hidden])');await page.locator('#clip-tools').evaluate(e=>e.open=true);await page.locator('#clip-export').click();await page.waitForFunction(()=>document.querySelector('#clip-status')?.textContent.includes('この1本を端末内に保存しました'),null,{timeout:30000});const clips=await page.evaluate(async()=>{const {listTemporaryVideos}=await import('/src/storage.js');return (await listTemporaryVideos()).map(r=>({id:r.id,kind:r.kind,shotId:r.shotId,start:r.start,end:r.end,bytes:r.bytes}));});assert.equal(clips.filter(r=>r.kind==='shot-clip').length,1);assert.ok(clips.some(r=>r.kind!=='shot-clip'));assert.match(await page.locator('#clip-download').textContent(),/ダウンロード/);await page.locator('[data-quick=correct]').click();await page.locator('#clip-range').click();assert.match(await page.locator('#clip-status').textContent(),/未保存/);assert.equal(await page.locator('[data-quick=correct]').getAttribute('aria-pressed'),'true');
 // Atomic capacity failure leaves original segment, generated clip and other data untouched.
 await page.evaluate(async()=>{const {saveShotClip,listTemporaryVideos}=await import('/src/storage.js');const before=await listTemporaryVideos();try{await saveShotClip({id:'too-big',bytes:100,blob:new Blob(['x'])},1);throw new Error('must fail');}catch(e){if(!e.message.includes('容量上限'))throw e;}if((await listTemporaryVideos()).length!==before.length)throw new Error('changed on failure');});
 await page.getByRole('button',{name:'Shot Review',exact:true}).click();await page.locator('[data-review-case]').first().click();await page.locator('#quick-playback details').last().evaluate(e=>e.open=true);await page.getByRole('button',{name:'このシュートの姿勢を再生',exact:true}).click();await page.waitForSelector('.pose-review-canvas:not([hidden])');await page.waitForTimeout(3000);await page.getByRole('button',{name:'Shot Review',exact:true}).click();await page.locator('#review-filter').selectOption('all');
 // Removed source video is explicit and never becomes an empty black thumbnail.
 await page.evaluate(async()=>{const {listTemporaryVideos,deleteTemporaryVideo}=await import('/src/storage.js');for(const r of await listTemporaryVideos())await deleteTemporaryVideo(r.id);});await page.getByRole('button',{name:'Shot Review',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('[data-thumbnail]')].some(t=>t.textContent==='動画なし'));assert.equal(await page.locator('.review-thumbnail video').count(),0);
 await page.getByRole('button',{name:'AIの改善',exact:true}).first().click();await page.waitForSelector('#ai-generate');assert.match(await page.locator('#ai-basic').textContent(),/セッション全体の評価は弱いフィードバック/);assert.equal(await page.locator('.ai-flow li').count(),4);await page.locator('#ai-generate').click();await page.waitForFunction(()=>document.querySelector('#ai-message').textContent.includes('まだ検証に必要'));assert.equal(await page.locator('[data-approve]').count(),0);
 await page.getByRole('button',{name:'Live Coach',exact:true}).click();await page.evaluate(()=>window.__deny=true);await page.locator('#live-start').click();await page.waitForFunction(()=>document.querySelector('#live-status').textContent.includes('拒否'));assert.equal(await page.locator('#coach-start').isEnabled(),false);assert.deepEqual(errors,[]);
 console.log('PASS Issue #5: absent/partial/static pose, re-entry, real synthetic shots, bounded inference, observed ball/loss, manual Hoop/rotation, 2pt/3pt persistence, record preference, portrait/landscape, real single-shot clip/save, atomic failure, pose playback, no-video states, AI steps and camera denial. Physical iPhone Safari not tested.');
}finally{await browser.close();}
