import {cameraGuidance} from './coach-camera-guidance.js';
import {mountLivePose} from './live-pose.js';
import {analyzeCompletedShot,compactAnalysis} from './coach-analysis.js';
import {selectCoachFeedback,FOCUS_LABELS} from './coach-feedback.js';
import {summarizeCoach,buildCoachInput} from './coach-summary.js';
import {CoachVoice} from './coach-voice.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const score=v=>Number.isFinite(v)?`${Math.round(v)}%`:'—';
const opts=(values,selected)=>Object.entries(values).map(([v,label])=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(label)}</option>`).join('');
const confidence={High:'高',Medium:'中（時刻は推定）',Low:'低・参考値'};
export function coachSummaryHTML(session){
 const s=summarizeCoach(session.shots);
 return `<section class="panel coach-summary"><h2>Live Coach · Session Summary</h2><p>${esc(session.goodFormReference.title)} · ${new Date(session.createdAt).toLocaleString('ja-JP')} · ${session.endedAt?'終了':'中断／練習中の記録'}</p><dl><dt>Total shots</dt><dd>${s.total}</dd><dt>Average Form Match</dt><dd>${score(s.average)}</dd><dt>Best shot</dt><dd>${score(s.best)}${s.bestShot?` · Shot ${s.bestShot}`:''}</dd><dt>Most consistent metric</dt><dd>${esc(s.mostConsistent?.label??'信頼できる計測が3本以上必要です')}</dd><dt>Most common deviation</dt><dd>${esc(s.mostCommon?.label??'十分なデータなし')}</dd><dt>First / Middle / Final third</dt><dd>${s.thirds.map(score).join(' / ')}</dd><dt>Next Session Focus</dt><dd>${esc(s.nextFocus.label)}</dd></dl><p>${esc(s.nextFocus.reason)}</p><p class="fineprint">平均には低信頼度の参考点も含みます。各3区間は本数順です。安定性・修正対象は低信頼度を除外して集計します。疲労・成功率の判定は行いません。</p><div class="table-scroll"><table><thead><tr><th>Shot</th><th>Form Match</th><th>Confidence</th><th>Feedback</th></tr></thead><tbody>${session.shots.map(s=>`<tr><td>${s.number}<br><button class="secondary" data-open-review="live:${esc(session.id)}:${s.number}">Shot Review</button></td><td>${score(s.comparison.overall)}</td><td>${confidence[s.comparison.confidence]}</td><td>${esc(s.coachFeedback.text.ja)}<details><summary>分析・助言の理由</summary><p>${esc(s.coachFeedback.reason)}</p><p>${s.comparison.groups.map(g=>`${esc(g.label)}: ${score(g.score)}`).join(' · ')}</p><p>${esc(s.coachFeedback.suppressedReason??'')}</p></details></td></tr>`).join('')}</tbody></table></div></section>`;
}
export function mountLiveCoach(container,{videos,referenceId,onSave}){
 const references=videos.filter(v=>v.analysis&&!v.isSession);
 container.innerHTML=`<section class="panel"><p class="eyebrow">LIVE COACH v0.3 · EXPERIMENTAL</p><h2>Live Coach</h2><p>Good Formと同じ撮影角度で、全身を映してください。開始後は検出した1本ごとに短い助言を1つ返します。</p><div class="metadata-grid"><label class="field">Good Form<select id="coach-reference">${references.length?references.map(v=>`<option value="${esc(v.id)}" ${v.id===referenceId?'selected':''}>${esc(v.title)}</option>`).join(''):'<option value="">Good Formを先に登録してください</option>'}</select></label><label class="field">シュート種別<select id="coach-type">${opts({jump:'ジャンプシュート',set:'セットシュート',free:'フリースロー'},'jump')}</select></label><label class="field">撮影角度<select id="coach-angle">${opts({front:'正面',side:'横',diagonal:'45度'},'side')}</select></label><label class="field">シュートする手<select id="coach-hand">${opts({right:'右手',left:'左手'},'right')}</select></label><label class="field">SESSION FOCUS<select id="coach-focus">${opts(FOCUS_LABELS,'automatic')}</select></label></div><div class="sync-controls"><label><input id="coach-voice" type="checkbox" checked> Voice Feedback</label><label>音量 <input id="coach-volume" type="range" min="0" max="1" step="0.1" value="1"></label><label>言語 <select id="coach-language"><option value="ja">日本語</option><option value="en">English</option></select></label><button id="coach-voice-test" class="secondary">音声テスト</button></div><div class="sync-controls"><button id="coach-start" class="primary" disabled>Start Coaching</button><button id="coach-stop" class="secondary" disabled>Stop Session</button><label><input id="coach-debug" type="checkbox"> Coach Debug</label></div><p id="coach-status" role="status">Start Camera → Start Coaching</p><div class="coach-board"><div>SHOT <strong id="coach-count">0</strong></div><div>FORM MATCH <strong id="coach-score">—</strong></div><div class="coach-feedback">FEEDBACK <strong id="coach-feedback">準備中</strong></div><p>Session Average <b id="coach-average">—</b> · Confidence <b id="coach-confidence">—</b> · Focus <b id="coach-focus-label">Automatic</b></p></div><div id="coach-details" hidden></div></section><div id="coach-camera"></div><div id="coach-summary"></div>`;
 const el=id=>container.querySelector(`#${id}`);
 let active=null,buffer=[],pending=[],disposed=false,saveQueue=Promise.resolve(),lastDetectedAt=0,lastGuidanceAt=-Infinity;
 const text=(id,v)=>{el(id).textContent=v;};
 const voice=new CoachVoice({onError:message=>{if(!disposed)text('coach-status',message);}});
 function configureVoice(){voice.configure({enabled:el('coach-voice').checked,volume:el('coach-volume').value,language:el('coach-language').value});}
 function defaults(){const r=references.find(v=>v.id===el('coach-reference').value);if(r)for(const [id,key]of[['coach-type','shotType'],['coach-angle','cameraAngle'],['coach-hand','hand']])el(id).value=r[key];}
 defaults();el('coach-reference').onchange=defaults;
 function persist(session){session.summary=summarizeCoach(session.shots);session.coachInput=buildCoachInput(session);const snapshot=structuredClone(session);saveQueue=saveQueue.catch(()=>{}).then(()=>onSave(snapshot)).catch(()=>{if(!disposed)text('coach-status','保存できませんでした。端末の空き容量を確認してください。');});}
 function update(){const latest=active?.shots.at(-1),summary=summarizeCoach(active?.shots??[]);text('coach-count',summary.total);text('coach-score',score(latest?.comparison.overall));text('coach-average',score(summary.average));text('coach-confidence',confidence[latest?.comparison.confidence]??'—');text('coach-focus-label',FOCUS_LABELS[active?.focus??el('coach-focus').value]);text('coach-feedback',latest?.coachFeedback.text[voice.language]??'次のシュートをどうぞ');if(latest)el('coach-details').innerHTML=`<p>Shot ${latest.number} · ${score(latest.comparison.overall)}</p><p>${latest.comparison.groups.map(g=>`${esc(g.label)}: ${score(g.score)}`).join(' · ')}</p><p>${esc(latest.coachFeedback.reason)}</p><p>${esc(latest.coachFeedback.suppressedReason??'')}</p><p>${latest.comparison.warnings.map(esc).join('<br>')}</p><p>COMPLETEから表示まで ${latest.feedbackDelayMs} ms · リリース時刻: 推定（Low）</p>`;}
 function process(job,speak=true){if(job.done)return;job.done=true;clearTimeout(job.timer);try{const result=analyzeCompletedShot(job.frames,job.event,job.reference,job.session.metadata,job.aspect);const number=job.session.shots.length+1,timestamp=Date.now();const feedback=selectCoachFeedback(result.comparison,{focus:job.session.focus,recent:job.session.shots,now:timestamp,shotNumber:number});const delivered=speak&&!disposed&&active===job.session?voice.deliver(feedback):false;feedback.speak=delivered;job.session.shots.push({number,timestamp,detectorNumber:job.event.number,completedAt:job.completedAt,feedbackDelayMs:Math.round(performance.now()-job.completeTime),analysis:compactAnalysis(result.analysis),scoreVersion:result.comparison.version,goodFormReferenceId:job.session.goodFormReference.id,comparison:result.comparison,checkpointReview:result.checkpointReview,coachFeedback:feedback});persist(job.session);if(!disposed&&active===job.session)update();}catch(error){if(!disposed)text('coach-status',`分析できませんでした: ${error.message}`);}}
 function controls(){const coaching=!!active;el('coach-start').disabled=coaching||!camera.isRunning()||!references.length;el('coach-stop').disabled=!coaching;for(const id of ['coach-reference','coach-type','coach-angle','coach-hand','coach-focus'])el(id).disabled=coaching;}
 function finish(){voice.cancel();if(!active)return;const session=active;pending.filter(j=>j.session===session).forEach(j=>process(j,false));session.endedAt=Date.now();persist(session);active=null;pending=[];buffer=[];if(!disposed){el('coach-summary').innerHTML=coachSummaryHTML(session);text('coach-status','セッション終了。結果をこのブラウザの履歴に保存します。');controls();container.querySelector('#live-hand').disabled=false;}}
 const camera=mountLivePose(el('coach-camera'),{shouldDetect:()=>!!active,onStart:()=>controls(),onStop:()=>{finish();if(!disposed)controls();},onFrame:frame=>{buffer.push(frame);buffer=buffer.filter(f=>f.time>=frame.time-10);},onShot:event=>{if(!active)return;lastDetectedAt=performance.now();const reference=references.find(v=>v.id===active.goodFormReference.id);const job={session:active,reference,event,frames:buffer.filter(f=>f.time>=event.phases.start-.001&&f.time<=event.phases.end+.001),aspect:buffer.at(-1)?.aspect??1,completedAt:Date.now(),completeTime:performance.now(),done:false};pending=pending.filter(j=>!j.done);pending.push(job);job.timer=setTimeout(()=>process(job),500);}});
 // Keep the original Live Pose/debug controls, but hide diagnostic detail by default.
 el('coach-camera').querySelector('h2').textContent='Camera';el('coach-camera').querySelector('.instruction').textContent='全身が映る位置でStart Camera。Coach DebugとShotDetector Debug Modeで詳細を確認できます。';
 el('coach-camera').querySelector('#live-show-metrics').checked=false;el('coach-camera').querySelector('#live-metrics').hidden=true;
 el('coach-start').onclick=()=>{if(!camera.isRunning()||active)return;const reference=references.find(v=>v.id===el('coach-reference').value);if(!reference)return;configureVoice();voice.prime();buffer=[];lastDetectedAt=performance.now();lastGuidanceAt=-Infinity;active={id:crypto.randomUUID(),kind:'live-coach',version:'live-coach-0.3',createdAt:Date.now(),endedAt:null,goodFormReference:{id:reference.id,title:reference.title,shotType:reference.shotType,cameraAngle:reference.cameraAngle,hand:reference.hand,analysis:compactAnalysis(reference.analysis)},metadata:{shotType:el('coach-type').value,cameraAngle:el('coach-angle').value,hand:el('coach-hand').value},focus:el('coach-focus').value,shots:[]};camera.setHand(active.metadata.hand);el('coach-summary').innerHTML='';persist(active);update();controls();text('coach-status','コーチング中 · リリース時刻は推定です。成功／失敗・ボール追跡はこのモードでは行いません。');};
 el('coach-stop').onclick=finish;el('coach-debug').onchange=()=>el('coach-details').hidden=!el('coach-debug').checked;
 for(const id of ['coach-voice','coach-volume','coach-language'])el(id).onchange=()=>{configureVoice();if(active)update();};el('coach-voice-test').onclick=()=>{configureVoice();voice.say(voice.language==='ja'?'音声テストです':'Voice test');};
 if(!voice.available)text('coach-status','このブラウザでは音声合成を利用できません。画面の助言は利用できます。');
 const guidanceTimer=setInterval(()=>{if(!active||!camera.isRunning()||disposed||document.hidden)return;const now=performance.now();if(now-lastDetectedAt<12000||now-lastGuidanceAt<20000||pending.some(j=>!j.done))return;const latest=buffer.at(-1);if(!latest||now-latest.time*1000>1500)return;const guidance=cameraGuidance(buffer,active.metadata.hand);if(!guidance)return;lastGuidanceAt=now;voice.say(guidance.text[voice.language]);text('coach-status',guidance.text[voice.language]);},1000);
 return ()=>{clearInterval(guidanceTimer);finish();disposed=true;pending.forEach(j=>clearTimeout(j.timer));voice.cancel();camera();buffer=[];};
}
